// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntpqmytvgnkroiskmhzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cHFteXR2Z25rcm9pc2ttaHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxOTIxNjMsImV4cCI6MjA1NDc2ODE2M30.OFnmgFFyUqK41jBeiXwb0jD5-ITkx7rWdyIuVxh5BM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);